### ISSUE TITLE
Report failure on lambda instance timeout

### ISSUE THREAD

**Issue by dej611** [lambci/lambci#64] opened 2016-11-09 10:59 UTC
I've just had a LambCI instance taking longer than 300 seconds.
The latest report saved on S3 was registered at 294 seconds, but the Slack and Github hook has not been updated.

Would it be possible to report a failure in such case?

**Comment by mhart** [comment] 2016-11-09 14:21
Indeed! This is on the cards – this is a dupe of #30

**Closed by mhart** 2016-11-09 14:21 UTC
